modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Prunoideae/ProbeJS"
license = "GPLv3"

[[mods]]
modId = "probejs"
version = "${version}"
displayName = "ProbeJS"
authors = "Prunoideae"
description = '''
Improving your KubeJS scripting experience by generating auto-completions of all kinds.
'''
logoFile = "icon.png"

[[dependencies.probejs]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.probejs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.probejs]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_version},)"
